// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterAndConfirmAccount(arg1:string):Promise<void>;

export function UpdateBridge(arg1:string):Promise<void>;
