// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDubbing() {
  return window['go']['main']['App']['CreateDubbing']();
}

export function RegisterAndConfirmAccount(arg1) {
  return window['go']['main']['App']['RegisterAndConfirmAccount'](arg1);
}

export function UpdateBridge(arg1) {
  return window['go']['main']['App']['UpdateBridge'](arg1);
}
