// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterAndConfirmAccount(arg1) {
  return window['go']['main']['App']['RegisterAndConfirmAccount'](arg1);
}

export function SolveCaptcha() {
  return window['go']['main']['App']['SolveCaptcha']();
}

export function UpdateBridge(arg1) {
  return window['go']['main']['App']['UpdateBridge'](arg1);
}
