// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDubbingFile(arg1) {
  return window['go']['main']['App']['AddDubbingFile'](arg1);
}

export function ChooseFiles() {
  return window['go']['main']['App']['ChooseFiles']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetTorPath() {
  return window['go']['main']['App']['GetTorPath']();
}

export function RegisterAndConfirmAccount(arg1) {
  return window['go']['main']['App']['RegisterAndConfirmAccount'](arg1);
}

export function SetSavePath() {
  return window['go']['main']['App']['SetSavePath']();
}

export function SetTorPath() {
  return window['go']['main']['App']['SetTorPath']();
}

export function StartDubbing(arg1, arg2) {
  return window['go']['main']['App']['StartDubbing'](arg1, arg2);
}

export function UpdateBridge(arg1) {
  return window['go']['main']['App']['UpdateBridge'](arg1);
}
