// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDubbing():Promise<void>;

export function GetLanguages():Promise<{[key: string]: string}>;

export function RegisterAndConfirmAccount(arg1:string):Promise<void>;

export function UpdateBridge(arg1:string):Promise<void>;
